// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";
package shiftcrypto.bitbox02;

import "common.proto";

enum XMRNetwork {
  XMRMainnet = 0;
  XMRTestnet = 1;
  XMRStagenet = 2;
}

message XMRAddressRequest {
  XMRNetwork network = 1;
  bool display = 2;
  repeated uint32 spend_keypath = 3;
  repeated uint32 view_keypath = 4;
}

message XMRSignTransactionRequest {
  message Output {
    string destination_address = 1;
    uint64 amount = 2;
  }

  XMRNetwork network = 1;
  repeated uint32 spend_keypath = 2;
  // 32-byte precomputed signing digest.
  bytes sighash = 3;
  repeated Output outputs = 4;
  uint64 fee = 5;
}

message XMRSignTransactionResponse {
  bytes signature = 1;
  bytes public_key = 2;
}

message XMRSignMessageRequest {
  repeated uint32 spend_keypath = 1;
  bytes msg = 2;
  XMRNetwork network = 3;
  repeated uint32 view_keypath = 4;
}

message XMRSignMessageResponse {
  bytes signature = 1;
  bytes public_key = 2;
}

message XMRRequest {
  oneof request {
    XMRAddressRequest address = 1;
    XMRSignTransactionRequest sign_transaction = 2;
    XMRSignMessageRequest sign_message = 3;
  }
}

message XMRResponse {
  oneof response {
    PubResponse pub = 1;
    XMRSignTransactionResponse sign_transaction = 2;
    XMRSignMessageResponse sign_message = 3;
  }
}
